GoTVisma/Models/GameOfThrones.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GoTVisma.Models
{
    public class GameOfThrones
    {
        public string CharacterLink { get; set; }
        public string HouseName { get; set; }
        public string SwornMembers { get; set; }
    }
}

GoTVisma/Controllers/GameOfThronesController.cs
using GoTVisma.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoTVisma.Controllers
{
    public class GameOfThronesController : Controller
    {
        // GET: GameOfThrones
        public ActionResult GoTBrowser()
        {
            var houses = new List<GameOfThrones>();
            var housesListAPI = GoTAPI.House.GetListOfHouses();
            foreach (var houseAPI in housesListAPI)
            {
                var house = new GameOfThrones();
                house.CharacterLink = houseAPI.url;
                house.HouseName = houseAPI.name;

                var swornMembersList = GoTAPI.Character.GetCharacterBySwornMembers(houseAPI.swornMembers);

                foreach (var swormMember in swornMembersList)
                    if (!string.IsNullOrEmpty(swormMember.name))
                        house.SwornMembers += "<li>" + swormMember.name.ToString() + "</li>";
                houses.Add(house);
            }

            return View(houses);
        }
    }
}

GoTVisma/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoTVisma.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GoTVisma/Views/GameOfThrones/GoTBrowser.cshtml
@model IEnumerable<GoTVisma.Models.GameOfThrones>

@{
    ViewBag.Title = "Browes";
}

<h2>Game Of Thrones</h2>
<div>
    <fieldset>
        <div style="height: 200px; width: 40%; overflow: auto; float:left;">
            @foreach (var house in Model)
            {
                <a class="btn btn-block"
                   onclick="setSwornMembers('@house.SwornMembers')">
                    @house.HouseName
                </a>
            }
        </div>

        <div style="height: 200px; width: 60%; overflow: auto; float:right;">


            <p id="prop"></p>


            <script>
                function setSwornMembers(swornMembers) {
                    document.getElementById("prop").innerHTML = "<ul>" + swornMembers + "</ul>";
                }
            </script>


        </div>
    </fieldset>
</div>

GoTVisma/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GoTVisma/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GoTVisma/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

GoTVisma/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Game Of Thrones click me :)", "GoTBrowser", "GameOfThrones", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "GoTBrowser", "GameOfThrones")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application for Visma</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>